# -*- coding: utf-8 -*-
"""Hello.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uwTMeAktc-qAcdz-JHi-t6sxtUnRxNaz
"""

print('Hello world')